"""initial migration

Revision ID: 497ce1d0237d
Revises: 
Create Date: 2026-09-28 11:55:07.831980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497ce1d0237d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
